name: Lint

run-name: Check code styles

on:
  push:
    branches:
      - main

jobs:
  run-nextjs-linter:
    name: Run Next.js Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: yarn install

      - run: |
          yarn lint
