name: Test

concurrency:
  cancel-in-progress: true
  group: ${{ format('{0} {1}', github.workflow, github.ref) }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # cause this composite actions haven't been merged into default branch, so you'll have to use a `ref` pointer to find it,
      # otherwise, it shall look like this.
      # - uses: ./.github/actions/prepare-node
      - uses: ./.github/actions/prepare-node@feat/add-composite-actions-prepare-nodejs
        with:
          node-version: 20

      - run: yarn lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prepare-node@feat/add-composite-actions-prepare-nodejs
        with:
          node-version: 20

      - run: yarn test

  deployment:
    name: Deployment
    uses: ./.github/workflows/deployment.yml
    if: ${{ github.event_name == 'push' }}
    needs: [lint, unit-test]
    secrets: inherit
    with:
      environment: preview
