name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: yarn install

      - run: yarn lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: yarn install

      - run: yarn test

  deployment-preview:
    name: Deployment (Preview)
    uses: ./.github/workflows/deployment.yml
    if: ${{ github.event_name == 'push' }}
    needs: [lint, unit-test]
    secrets: inherit
    with:
      environment: preview
